[2024-02-29T21:34:10.709+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v3.second_task manual__2024-02-29T21:34:08.796180+00:00 [queued]>
[2024-02-29T21:34:10.715+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v3.second_task manual__2024-02-29T21:34:08.796180+00:00 [queued]>
[2024-02-29T21:34:10.715+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 6
[2024-02-29T21:34:10.723+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): second_task> on 2024-02-29 21:34:08.796180+00:00
[2024-02-29T21:34:10.728+0000] {standard_task_runner.py:60} INFO - Started process 2080 to run task
[2024-02-29T21:34:10.731+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'second_task', 'manual__2024-02-29T21:34:08.796180+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmp7zh981_j']
[2024-02-29T21:34:10.752+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask second_task
[2024-02-29T21:34:10.944+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag_v3.second_task manual__2024-02-29T21:34:08.796180+00:00 [running]> on host 417e643aed36
[2024-02-29T21:34:13.410+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dn' AIRFLOW_CTX_DAG_ID='our_first_dag_v3' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-29T21:34:08.796180+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-29T21:34:08.796180+00:00'
[2024-02-29T21:34:13.412+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-02-29T21:34:13.414+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey,I am task2 and will be running after task1!']
[2024-02-29T21:34:13.429+0000] {subprocess.py:86} INFO - Output:
[2024-02-29T21:34:13.434+0000] {subprocess.py:93} INFO - hey,I am task2 and will be running after task1!
[2024-02-29T21:34:13.435+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-02-29T21:34:13.478+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=second_task, execution_date=20240229T213408, start_date=20240229T213410, end_date=20240229T213413
[2024-02-29T21:34:13.578+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-29T21:34:13.659+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
